anchor_version = "0.20.1"
solana_version = "1.9.5"

[programs.localnet]
voter_stake_registry = "3GepGwMp6WgPqgNa5NuSpnw3rQjYnqHCcVWhVmpGnw6s"

[programs.devnet]
voter_stake_registry = "3GepGwMp6WgPqgNa5NuSpnw3rQjYnqHCcVWhVmpGnw6s"

[programs.mainnet]
voter_stake_registry = "3GepGwMp6WgPqgNa5NuSpnw3rQjYnqHCcVWhVmpGnw6s"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
