name: Linter

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_STABLE_VERSION: "1.66.1"

defaults:
  run:
    working-directory: ./

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install stable Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE_VERSION }}
          components: clippy
          cache: true

      - name: Install nightly Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          cache: true

      - name: Set default Rust toolchain
        run: |
          rustup show 
          rustup override set ${{ env.RUST_STABLE_VERSION }}

      - name: Run fmt
        run: cargo +nightly fmt -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings --allow=clippy::result_large_err --allow=clippy::await_holding_refcell_ref